services:
  pgsql:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=PGUSER
      - POSTGRES_PASSWORD=PGPASSWORD
    ports:
      - '5432:5432'
    volumes: 
      - pgsql-db:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  telegram-bot:
    build:
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN
      - OPENAI_API_KEY
      - PGUSER
      - PGHOST=pgsql
      - PGPASSWORD
      - PGDATABASE
      - REDIS_URL=redis
    depends_on:
      - pgsql
      - redis
    volumes:
      - .:/app
    working_dir: /app


volumes:
  pgsql-db:
    driver: local
  redis-data:
    driver: local
