version: '3.8'
services:
  pgsql:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - pgsql-db:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  pgsql-db:
    driver: local
  redis-data:
    driver: local